name: Build and publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          login-server: 'https://index.docker.io/v1/'
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: |
          docker build -t ${{ github.repository }} .
          docker tag ${{ github.repository }}:latest ${{ github.repository }}:${{ github.sha }}
          docker push ${{ github.repository }}

